trigger: none

pool: chaukidar

variables:
  subscrip: 5e4fafbb-ef69-4e17-8835-68030d81f758
  az_service: CICD_service

parameters:
  - name: Environment 
    type: string
    default: dev
    values:
      - dev
      - Qa
      - prod
      - pre prod

  - name: init
    type: boolean
    default: "false"

  - name: validate
    type: boolean
    default: "false"

  - name: plan
    type: boolean
    default: "false"

  - name: apply
    type: boolean
    default: "false"

steps:
- task: TerraformInstaller@1
  displayName: "terraform install ho raha"
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: "terraform init chal raha hai"
  condition: '${{parameters.init}}'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: '$(az_service)'
    backendAzureRmStorageAccountName: rajatstg
    backendAzureRmContainerName: rajcontainer
    backendAzureRmKey: raj.tfstate

- task: TerraformTask@5
  displayName: 'terraform validate'
  condition: '${{parameters.validate}}'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: 'terraform plan'
  condition: '${{parameters.plan}}'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: '$(az_service)'
    environmentAzureRmOverrideSubscriptionID: '$(subscrip)'
- task: TerraformTask@5
  displayName: 'terraform apply'
  condition: '${{parameters.apply}}'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: '$(az_service)'
    environmentAzureRmOverrideSubscriptionID: '$(subscrip)'